// en/developer/appdev/code/react-guestbook/after/react-guestbook-app-migrated/src/add-entry.js
import React from 'react';
import { Link } from 'react-router-dom';

class EntryForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: '',
      message: ''
    };
  }

  handleChange(event) {
    this.setState({[event.target.name]: event.target.value});
  }
  
  handleClick(event) {
    if(this.state.name !== '' && this.state.message !== ''){
      this.props.addMethod(this.state.name, this.state.message);
    }
    else {
      alert('you must fill in all fields');
    }
  }
  
  render() {

      return (
        <form>
          <div className="form-group">
            <label htmlFor="addEntryNameInput">Name</label>
            <input className="form-control" id="addEntryNameInput" value={this.state.name} onChange={this.handleChange.bind(this)} name="name" aria-label="name" />
          </div>
          <div className="form-group mb-4">
            <label htmlFor="addEntryMessageInput">Message</label>
            <input className="form-control" id="addEntryMessageInput" value={this.state.message} onChange={this.handleChange.bind(this)} name="message" aria-label="message" />
          </div>
          <button type="button" className="btn btn-primary mr-2" onClick={this.handleClick.bind(this)}>Save</button>
          <Link to="/view-guestbook" className="btn btn-outline-secondary">Cancel</Link>
        </form>
      );
  }
}

export default EntryForm;

// en/developer/appdev/code/vue-guestbook/after/vue-guestbook-migrated/src/components/AddEntry.vue
<template>
  <div class="ml-2 mr-2">
    <form>
      <fieldset>
        <div class="form-group">
          <label for="addEntryNameInput">Name</label>
          <input class="form-control" id="addEntryNameInput" name="name" v-model="name" aria-label="name" />
        </div>
        <div class="form-group mb-4">
          <label for="addEntryMessageInput">Message</label>
          <input class="form-control" id="addEntryMessageInput" name="message" v-model="message" aria-label="message" />
        </div>
      </fieldset>

      <div class="button-footer">  
        <button type="button" class="btn btn-primary mr-2" v-on:click="add(name, message)">Save</button>
        <routerLink to="/view-guestbook" class="btn btn-outline-secondary">Cancel</routerLink>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'AddEntry',
  data: function() {
    return {
    name: '',
    message: '' 
    }
  },
  props: ['add']
}
</script>
